<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>markdown</string>
		<string>txt</string>
		<string>journal</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^(\d){4}\-(\d){2}\-(\d){2} \| (\d){2}:(\d){2}+(.*)$</string>
	<key>foldingStopMarker</key>
	<string>^\*\*\*$</string>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>JournalTasks</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\[(.*)\]$\n</string>
			<key>name</key>
			<string>markup.tg.markdown</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(\d){4}\-(\d){2}\-(\d){2} \| (\d){2}:(\d){2}+(.*)$</string>
			<key>name</key>
			<string>markup.datehdr.markdown</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#link</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.list_item.leading.tasks</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.tasks</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.paragraph.list.tasks</string>
			<key>match</key>
			<string>^(\s*)(-)(.*@done)\n</string>
			<key>name</key>
			<string>markup.list.completed.tasks</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.list_item.leading.tasks</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.tasks</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.paragraph.list.tasks</string>
			<key>match</key>
			<string>^(\s*)(-).*\n</string>
			<key>name</key>
			<string>markup.list.pending.tasks</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.list_item.leading.tasks</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.header.tasks</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.toc-list.tasks</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.header.tasks</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*)((.+)(:)\s*$\n?)</string>
			<key>name</key>
			<string>meta.header-line.tasks</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>link</key>
		<dict>
			<key>match</key>
			<string>(https?|ftp|mailto):\S+?(?=[)&gt;,.':;"]*(\s|$)|$)</string>
			<key>name</key>
			<string>markup.underline.link.tasks</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.journal</string>
	<key>uuid</key>
	<string>5326248E-17D0-4384-AD7E-288C3BCC9356</string>
</dict>
</plist>
